name: generate

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Check out
        uses: actions/checkout@v2
      # 処理を高速化するために環境をキャッシュ
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  pb:
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: initialize go
        run: go mod init
      - name: install protoc
        run: |
          go get -v google.golang.org/protobuf/cmd/protoc-gen-go
          go get -v google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: exist protoc
        run: protoc
      - name: compile protocol-buffers
        run: make hello-gen
      - name: ls
        run: ls
