name: generate

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
        id: go
      - name: Check out
        uses: actions/checkout@v2
      # 処理を高速化するために環境をキャッシュ
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  pb:
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: initialize go
        run: go mod init github.com/Hirochon/aggregation-pb
      - name: get protoc
        run: |
          go get -v google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go get -v google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      - name: compile protocol-buffers
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          protoc --go_out=. --go_opt=paths=source_relative \
            --go-grpc_out=. --go-grpc_opt=paths=source_relative \
            hello/proto/hello.proto
      - name: ls
        run: ls hello/proto/

  dispatch-target-updated:
    needs: pb
    name: dispatch-target-updated
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        repo: ['Hirochon/chon-go-micro-packages']
    steps:
      - name: ls
        run: ls hello/proto/
      # - name: dispatch target-updated
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      #     repository: ${{ matrix.repo }}
      #     event-type: target-updated
